.TH "Cola_max.h" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cola_max.h \- Fichero cabecera de ColaMax\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'elemento\&.h'\fP
.br
\fC#include <stack>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBCola_Max\fP"
.br
.RI "ColaMax \fBCola_Max\fP implementada a partir de una Pila Stack de la STL :) "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera de ColaMax\&. 

Gestiona una secuencia de elementos con estructura de cola en la que encontramos dos objetos, el elemento de la cola front, el back y el mayor valor hasta el momento 
.PP
Definición en el archivo \fBCola_max\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
