.TH "elemento" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elemento
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBele\fP"
.br
.ti -1c
.RI "int \fBmaximo\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 6 del archivo elemento\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
