.TH "Pila_max_Cola" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pila_max_Cola \- T\&.D\&.A\&. Pila_max\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pila_max_Cola\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBPila_max_Cola\fP ()"
.br
.RI "Constructor sin parámetro que incializa la pila vacía\&. "
.ti -1c
.RI "\fBPila_max_Cola\fP (\fBPila_max_Cola\fP &copia)"
.br
.RI "Constructor de copia que copia los elementos de una pila_max a otra\&. "
.ti -1c
.RI "\fBPila_max_Cola\fP & \fBoperator=\fP (\fBPila_max_Cola\fP &otra)"
.br
.RI "Operador de asignación para \fBPila_max_Cola\fP\&. "
.ti -1c
.RI "bool \fBvacia\fP () const"
.br
.RI "Indica si la pila se encuentra vacía o no\&. "
.ti -1c
.RI "\fBelemento\fP \fBtope\fP ()"
.br
.RI "Devuelve el elemento que hay en el tope de la pila\&. "
.ti -1c
.RI "void \fBponer\fP (const int elem)"
.br
.RI "Añade un elemento a la pila haciéndose cargo de actualizar el máximo\&. "
.ti -1c
.RI "void \fBquitar\fP ()"
.br
.RI "Elimina el elemento que hay en el tope de la pila\&. "
.ti -1c
.RI "int \fBnum_elementos\fP () const"
.br
.RI "Dice el número de elemento que tiene la pila\&. "
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "void \fBcopiar\fP (\fBPila_max_Cola\fP &otra, unsigned int elem_dejar=0)"
.br
.RI "Copia una pila en otra\&. "
.ti -1c
.RI "void \fBborrar\fP ()"
.br
.RI "Borra la pila\&. "
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "\fBCola\fP< \fBelemento\fP > \fBcola\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
T\&.D\&.A\&. Pila_max\&. 

Una instancia \fIc\fP del tipo de dato abstracto \fC\fBPila_max_Cola\fP\fP es un objeto que representa una estructura de datos que funciona tal cual funcionan las colas tradicionales\&. La peculiaridad de esta cola es que guarda parejas de valores\&. Así, el primer elemento es el elemento normal con el que trabajamos y el segundo representa el valor máximo introducido en la cola hasta el momento\&.
.PP
Para esta versión en concreto, se utiliza un T\&.D\&.A\&. \fIcola\fP propio
.PP
\fBAutor\fP
.RS 4
Darío Megías Guerrero y María Sánchez Marcos 
.RE
.PP
\fBFecha\fP
.RS 4
Diciembre 2020 
.RE
.PP

.PP
Definición en la línea 33 del archivo Pila_max_Cola\&.h\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "Pila_max_Cola::Pila_max_Cola (\fBPila_max_Cola\fP & copia)"

.PP
Constructor de copia que copia los elementos de una pila_max a otra\&. 
.PP
\fBParámetros\fP
.RS 4
\fIcopia\fP Instancia de \fBPila_max_Cola\fP a copiar\&. 
.RE
.PP

.PP
Definición en la línea 20 del archivo Pila_max_Cola\&.cpp\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "void Pila_max_Cola::copiar (\fBPila_max_Cola\fP & otra, unsigned int elem_dejar = \fC0\fP)\fC [private]\fP"

.PP
Copia una pila en otra\&. 
.PP
\fBParámetros\fP
.RS 4
\fIotra\fP Pila a copiar 
.RE
.PP

.PP
Definición en la línea 3 del archivo Pila_max_Cola\&.cpp\&.
.SS "int Pila_max_Cola::num_elementos () const"

.PP
Dice el número de elemento que tiene la pila\&. 
.PP
\fBDevuelve\fP
.RS 4
Valor entero que representa el número de elementos que hay almacenados en al pila 
.RE
.PP

.PP
Definición en la línea 58 del archivo Pila_max_Cola\&.cpp\&.
.SS "\fBPila_max_Cola\fP & Pila_max_Cola::operator= (\fBPila_max_Cola\fP & otra)"

.PP
Operador de asignación para \fBPila_max_Cola\fP\&. 
.PP
\fBParámetros\fP
.RS 4
\fIotra\fP Es el \fIright-value\fP en la asignación 
.RE
.PP
\fBDevuelve\fP
.RS 4
Devuleve a la nueva pila una vez hecha la asignación\&. 
.RE
.PP

.PP
Definición en la línea 24 del archivo Pila_max_Cola\&.cpp\&.
.SS "void Pila_max_Cola::poner (const int elem)"

.PP
Añade un elemento a la pila haciéndose cargo de actualizar el máximo\&. 
.PP
\fBParámetros\fP
.RS 4
\fIelem\fP Valor entero a poner en la pila 
.RE
.PP

.PP
Definición en la línea 44 del archivo Pila_max_Cola\&.cpp\&.
.SS "\fBelemento\fP Pila_max_Cola::tope ()"

.PP
Devuelve el elemento que hay en el tope de la pila\&. 
.PP
\fBDevuelve\fP
.RS 4
Un dato \fIstruct\fP que contiene el último valor almacenado en la pila y el valor máximo almacenado hasta el momento\&. 
.RE
.PP

.PP
Definición en la línea 34 del archivo Pila_max_Cola\&.cpp\&.
.SS "bool Pila_max_Cola::vacia () const"

.PP
Indica si la pila se encuentra vacía o no\&. 
.PP
\fBDevuelve\fP
.RS 4
Valor booleano que estará a \fItrue\fP si la pila está vacía\&. 
.RE
.PP

.PP
Definición en la línea 30 del archivo Pila_max_Cola\&.cpp\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "\fBCola\fP<\fBelemento\fP> Pila_max_Cola::cola\fC [private]\fP"

.PP
.nf
@page repPila_max_Cola Rep del TDA Pila_max_Cola

@section invPila_max_cola Invariante de la representación

El invariante es:

.fi
.PP
 Para todo \fIrep\&.cola\&.frente()\fP\&.ele = \fIe\fP, entonces \fIrep\&.cola\&.frente()\fP\&.maximo >= \fIe\fP\&. 
.PP
.nf
@section faPila_max_Cola Función de abstracción

Un objeto válido @e rep del TDA Cola_max_Cola representa a una

.fi
.PP
 estructura de datos que se comporta como una \fCpila\fP que almacena datos del tipo \fCelemento\fP\&. Estos son parejas valor-maximo\&.
.PP
Si la pila tiene \fIn\fP elementos y el tope es el elemento n-ésimo: | rep\&.cola[n] | Corresponde con rep\&.cola\&.ultima\&. | rep\&.cola[n-1] | | \&.\&.\&. | | rep\&.cola[0] | Corresponde con rep\&.cola\&.primera\&. 
.PP
Definición en la línea 57 del archivo Pila_max_Cola\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
