.TH "Pila_max_Cola" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pila_max_Cola
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBPila_max_Cola\fP (const \fBPila_max_Cola\fP &copia)"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "\fBCola\fP< \fBelemento\fP > \fBcola\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 7 del archivo Pila_max_Cola\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
