.TH "Pila_max_Cola.h" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pila_max_Cola.h \- Fichero de cabecera asociado a la pila de pares valor-máximo\&. Implementacion del TDA \fBPila_Max\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <elemento\&.h>\fP
.br
\fC#include <cola\&.h>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPila_Max\fP"
.br
.RI "T\&.D\&.A\&. \fBPila_Max\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero de cabecera asociado a la pila de pares valor-máximo\&. Implementacion del TDA \fBPila_Max\fP\&. 


.PP
\fBAutor\fP
.RS 4
Darío Megías Guerrero & María Sánchez Marcos 
.RE
.PP
\fBFecha\fP
.RS 4
5 Oct 2020 
.RE
.PP
\fBCopyright\fP
.RS 4
2020 Darío Megías Guerrero & María Sanchez Marcos 
.RE
.PP

.PP
Definición en el archivo \fBPila_max_Cola\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
