.TH "Pila_max_VD.h" 3 "Domingo, 6 de Diciembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pila_max_VD.h \- Fichero cabecera del TDA PilaMAX\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'elemento\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPila_Max\fP"
.br
.RI "T\&.D\&.A\&. \fBPila_Max\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA PilaMAX\&. 

Gestiona una secuencia de elementos con estructura de pila en la que encontramos dos objetos, el elemento de la pila y el tope hasta el momento 
.PP
Definición en el archivo \fBPila_max_VD\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
