.TH "imagen.h" 3 "Martes, 10 de Noviembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.h \- Fichero de cabecera asociado a la biblioteca libimg\&.a\&. Implementacion del TDA imagen (imagen digital en niveles de gris)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <imagenES\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBImagen\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.RI "T\&.D\&.A\&. \fBImagen\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero de cabecera asociado a la biblioteca libimg\&.a\&. Implementacion del TDA imagen (imagen digital en niveles de gris)\&. 


.PP
\fBAutor\fP
.RS 4
Darío Megías Guerrero & María Sánchez Marcos 
.RE
.PP
\fBFecha\fP
.RS 4
22 Oct 2020 
.RE
.PP
\fBCopyright\fP
.RS 4
2020 Darío Megías Guerrero & María Sanchez Marcos 
.RE
.PP

.PP
Definición en el archivo \fBimagen\&.h\fP\&.
.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef unsigned char \fBbyte\fP"

.PP
T\&.D\&.A\&. \fBImagen\fP\&. Una instancia \fIc\fP del tipo de dato abstracto \fC\fBImagen\fP\fP es un objeto que representa una imagen como una sucesión de píxeles dispuesta en filas y columnas\&. Los píxeles representan valores de luminosidad de la pantalla\&. Además almacena el número de filas de la imagen y su número de columnas\&.
.PP
\fBAutor\fP
.RS 4
Darío Megías Guerrero y María Sánchez Marcos 
.RE
.PP
\fBFecha\fP
.RS 4
Noviembre 2020 
.RE
.PP

.PP
Definición en la línea 31 del archivo imagen\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
