.TH "imagen.cpp" 3 "Martes, 10 de Noviembre de 2020" "TDA Imagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.cpp \- Implementación del TDA \fBImagen\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <imagen\&.h>\fP
.br

.SH "Descripción detallada"
.PP 
Implementación del TDA \fBImagen\fP\&. 


.PP
Definición en el archivo \fBimagen\&.cpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para TDA Imagen del código fuente\&.
